name: twenty

services:
  server:
    image: twentycrm/twenty:latest
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    ports:
      - "3000:3000"
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/default
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      DISABLE_DB_MIGRATIONS: ${DISABLE_DB_MIGRATIONS}
      DISABLE_CRON_JOBS_REGISTRATION: ${DISABLE_CRON_JOBS_REGISTRATION}
      
      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      
      APP_SECRET: ${APP_SECRET:-replace_me_with_a_random_string}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:-replace_with_access_token_secret}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET:-replace_with_login_token_secret}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-replace_with_refresh_token_secret}

    depends_on:
      - db
      - redis

  worker:
    image: twentycrm/twenty:latest
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command: yarn worker:prod
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/default
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      
      APP_SECRET: ${APP_SECRET:-replace_me_with_a_random_string}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:-replace_with_access_token_secret}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET:-replace_with_login_token_secret}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-replace_with_refresh_token_secret}

    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD:-postgres}
      POSTGRES_USER: ${PG_DATABASE_USER:-postgres}
      POSTGRES_DB: default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_DATABASE_USER:-postgres} -d default"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  db-data:
  redis-data:
  server-local-data: